apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-dev
spec:
  destination:
    namespace: jenkins
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://charts.jenkins.io'
    chart: jenkins
    targetRevision: '4.8.1'
    helm:
      valueFiles:
      - $values/values-dev.yaml
  - repoURL: 'https://github.com/charlieboom/jenkins.git'
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

