controller:
  JCasC:
    welcome-message: |
      jenkins:
        systemMessage: Welcome to our DEV CI\CD server.  This Jenkins is configured and managed 'as code' by Charlie Boom.
serviceType: NodePort